In [9]:
from adrs_warehouse.data.fetch import download_adr_data, build_ticker_dimension
from adrs_warehouse.data.transform import  clean_data, normalize_prices_long
from adrs_warehouse.database.operations import ADRDatabase

In [10]:
data = download_adr_data()
cleaned = clean_data(data)
long_normal = normalize_prices_long(cleaned)

Downloading data for 13 tickers from 2018-01-01...

[*********************100%***********************]  13 of 13 completed

Download complete. Shape: (2025, 65)

In [11]:
long_normal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26325 entries, 0 to 26324
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    26325 non-null  datetime64[ns]
 1   ticker  26325 non-null  object
 2   open    26248 non-null  float64
 3   high    26248 non-null  float64
 4   low     26248 non-null  float64
 5   close   26248 non-null  float64
 6   volume  26248 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 1.4+ MB

In [13]:
long_normal

            date ticker       open        high        low      close    volume
0     2018-01-02   SUPV  26.841580   27.557053  26.339207  27.440075  340300.0
1     2018-01-02   CEPU        NaN         NaN        NaN        NaN       NaN
2     2018-01-02    IRS  20.932400   22.299386  20.750136  22.292376   42216.0
3     2018-01-02   BIOX        NaN         NaN        NaN        NaN       NaN
4     2018-01-02    PAM  68.709999   69.739998  68.300003  69.160004  322400.0
...          ...    ...        ...         ...        ...        ...       ...
26320 2026-01-22   BBAR  18.459999   18.849199  18.280001  18.510000  595635.0
26321 2026-01-22   GGAL  54.250000   55.400002  53.490002  53.700001  677385.0
26322 2026-01-22    TEO  11.460000   12.910000  11.470000  12.590000  700451.0
26323 2026-01-22  CRESY  12.480000   12.920000  12.480000  12.700000  152943.0
26324 2026-01-22    BMA  98.709999  100.000000  96.830002  96.830002  181336.0

[26325 rows x 7 columns]

In [18]:
db = ADRDatabase(db_path='../data/processed/db.duckdb')

In [19]:
db.create_table_from_dataframe(long_normal, 'stock_prices')

In [21]:
db.query("SELECT * FROM stock_prices WHERE ticker = 'MELI' LIMIT 100")

         date ticker        open        high         low       close     volume
0  2018-01-02   MELI  317.489990  322.640015  316.269989  322.579987   366900.0
1  2018-01-03   MELI  324.670013  329.970001  322.500000  329.279999   443500.0
2  2018-01-04   MELI  329.890015  332.940002  322.549988  325.880005   389200.0
3  2018-01-05   MELI  329.200012  336.489990  328.600006  330.869995   589000.0
4  2018-01-08   MELI  328.119995  341.470001  327.660004  340.790009   491200.0
..        ...    ...         ...         ...         ...         ...        ...
95 2018-05-18   MELI  297.750000  304.660004  292.239990  295.369995   605500.0
96 2018-05-21   MELI  295.820007  298.829987  287.529999  290.600006   493500.0
97 2018-05-22   MELI  292.480011  297.549988  290.029999  294.760010   677300.0
98 2018-05-23   MELI  294.000000  307.640015  292.700012  304.790009   687300.0
99 2018-05-24   MELI  301.890015  316.480011  297.510010  314.929993  1383400.0

[100 rows x 7 columns]